version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
       - ./db:/docker-entrypoint-initdb.d

  web:
    build: ./web
    command: npm start
    environment:
      - PGUSER=postgres 
      - PGHOST=db
      - PGPASSWORD=password 
      - PGDATABASE=postgres 
      - PGPORT=5432 
      - PORT=8000
      - SERVER_IMAGE=itzg/minecraft-server
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    depends_on:
      - db
